# Generated by Django 5.1.7 on 2025-04-06 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('commence', 'Commencée'), ('en_cours', 'En cours'), ('termine', 'Terminée'), ('en_retard', 'En retard')], default='commence', max_length=10)),
                ('users', models.ManyToManyField(blank=True, related_name='taches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taches',
            },
        ),
    ]
