# Generated by Django 5.1.7 on 2025-04-06 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='users',
        ),
        migrations.AddField(
            model_name='tache',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('pas_debutee', 'Pas debutée'), ('en_cours', 'En cours'), ('termine', 'Terminée'), ('en_retard', 'En retard')], default='pas_debutee', max_length=20),
        ),
    ]
